- name: Prework 
  block: 
    - name: Update and upgrade all packages
      dnf:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install packages
      dnf:
        name: 
          - qemu-guest-agent
          - net-tools
          - curl
          - git
          - realmd 
          - sssd 
          - adcli
          - samba-common-tools
          - oddjob 
          - oddjob-mkhomedir
          - krb5-workstation
          - whois
        state: present

    - name: Enable qemu (but don't start it)
      systemd: 
        name: qemu-guest-agent
        enabled: true

- name: Install Docker 
  block: 
    - name: Install packages
      dnf:
        name: kernel-modules-extra
        state: present

    - name: Depmod to rebuild module dependencies
      shell: depmod -a

    - name: Add Docker CE repository
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: '0644'

    - name: Install Docker CE
      dnf:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Create groups
      group:
        name: "{{ item }}"
        state: present
      loop:
        - docker
        - sudo

    - name: Add the user loc_admin 
      user:
        name: loc_admin
        comment: Local Admin User
        create_home: true 
        shell: /bin/bash
        groups: sudo,docker
        append: true 

- name: Domain work
  block: 
    - name: Enable and start oddjob service
      systemd:
        name: oddjobd
        enabled: true
        state: started

    # - name: Join the domain
    #   shell: "echo '......' | realm -v join aut.lan --membership-software=samba"
    #   register: realm_join
    #   ignore_errors: true
    #   timeout: 60

    - name: Auto-make home directory 
      shell: authselect select sssd with-mkhomedir

    # - name: Set use_fully_qualified_names to False
    #   lineinfile:
    #     path: "/etc/sssd/sssd.conf"
    #     search_string: use_fully_qualified_names
    #     line: use_fully_qualified_names = False
    #   ignore_errors: true 

    # - name: Restart sssd
    #   service:
    #     name: sssd
    #     state: restarted 

- name: Install Tailscale
  block:
    - name: Add Tailscale repository
      get_url:
        url: https://pkgs.tailscale.com/stable/fedora/tailscale.repo
        dest: /etc/yum.repos.d/tailscale.repo
        mode: '0644'

    - name: Install Tailscale
      dnf:
        name: tailscale
        state: present
      
    - name: Enable IP forwarding
      lineinfile: 
        path: /etc/sysctl.d/99-tailscale.conf
        search_string: "{{ item }}"
        line: "{{ item }}"
        create: true 
      loop:
        - 'net.ipv4.ip_forward = 1'
        - 'net.ipv6.conf.all.forwarding = 1'

    - name: Apply sysctl settings
      shell: sysctl -p /etc/sysctl.d/99-tailscale.conf

    - name: Enable and start Tailscale service
      systemd:
        name: tailscaled
        enabled: true
        state: started

- name: App repo work 
  block:
    - name: Create directories
      file: 
        path: "/opt/loc_admin/app"
        state: directory

    - name: Clone app repo 
      git: 
        repo: https://github.com/zachneill/app.git
        dest: "/opt/loc_admin/app"
        version: main
    
    - name: Copy rootCA to system anchors directory
      copy:
        src: /opt/loc_admin/app/certs/rootCA.pem
        dest: /etc/pki/ca-trust/source/anchors/rootCA.pem
        owner: root
        group: root
        mode: '0644'
        remote_src: true

    - name: Update certs
      shell: update-ca-trust