- name: Prework 
  block: 
    - name: Update and upgrade all packages
      apt:
        name: "*"
        state: latest
        update_cache: true

    - name: Install packages
      apt:
        name: 
          - qemu-guest-agent
          - net-tools
          - curl
          - git
          - realmd 
          - sssd 
          - sssd-tools
          - adcli
          - krb5-user
          - samba-common-bin
          - whois
        state: present

    - name: Enable qemu (but don't start it)
      systemd: 
        name: qemu-guest-agent
        enabled: true
  become: true

- name: Install Docker 
  block: 
    - name: Create keyrings folder 
      file: 
        path: /etc/apt/keyrings
        state: directory 
        mode: "0755"

    - name: Add Docker gpg key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add template to sources 
      template: 
        src: docker.sources
        dest: /etc/apt/sources.list.d/docker.sources

    - name: Install Docker CE
      apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true

    - name: Create groups
      group:
        name: docker
        state: present
  become: true

- name: Install Tailscale
  block:
    - name: Add Tailscale gpg key
      get_url:
        url: https://pkgs.tailscale.com/stable/ubuntu/resolute.noarmor.gpg
        dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
        mode: '0644'

    - name: Add Tailscale repository
      get_url:
        url: https://pkgs.tailscale.com/stable/ubuntu/resolute.tailscale-keyring.list
        dest: /etc/apt/sources.list.d/tailscale.list
        mode: '0644'

    - name: Install Tailscale
      apt:
        name: tailscale
        state: present
        update_cache: true 
      
    - name: Enable IP forwarding
      lineinfile: 
        path: /etc/sysctl.d/99-tailscale.conf
        search_string: "{{ item }}"
        line: "{{ item }}"
        create: true 
      loop:
        - 'net.ipv4.ip_forward = 1'
        - 'net.ipv6.conf.all.forwarding = 1'

    - name: Apply sysctl settings
      shell: sysctl -p /etc/sysctl.d/99-tailscale.conf

    - name: Enable and start Tailscale service
      systemd:
        name: tailscaled
        enabled: true
        state: started
  become: true

- name: Platform repo work 
  block:
    - name: Create directory
      file: 
        path: "/opt/loc_admin/platform"
        state: directory
        owner: packer
      become: true

    - name: Clone app repo 
      git: 
        repo: https://github.com/zachneill/platform.git
        dest: "/opt/loc_admin/platform"
        version: main
    
    - name: Copy rootCA to cert directory
      copy:
        src: /opt/loc_admin/platform/certs/rootCA.pem
        dest: /usr/local/share/ca-certificates/rootCA.pem
        owner: root
        group: root
        mode: "0644"
        remote_src: true
      become: true

    - name: Update certs
      shell: update-ca-certificates
      become: true