- name: Domain work
  block: 
    - shell: whoami 
      register: who
    - debug:
        var: who
    - name: Join the domain
      shell: "echo '{{ admin_pw }}' | realm -v join aut.lan --membership-software=samba"
      register: realm_join
      timeout: 60

    - name: Set use_fully_qualified_names to False
      lineinfile:
        path: "/etc/sssd/sssd.conf"
        search_string: use_fully_qualified_names
        line: use_fully_qualified_names = False

    - name: Restart sssd
      service:
        name: sssd
        state: restarted 
  become: true